export const CARD_TYPES = [
  {
    id: "professional",
    label: "Professional",
    description: "Executives, managers & professionals",
    color: "#3b82f6",
    titleLabel: "Title / Role",
    placeholderTitle: "Product Manager at Acme Corp",
    placeholderBio: "Building products that matter. 10+ years in the industry.",
  },
  {
    id: "developer",
    label: "Developer",
    description: "Engineers, developers & tech folks",
    color: "#10b981",
    titleLabel: "Role",
    tagLabel: "Tech Stack",
    tagPlaceholder: "React, TypeScript, Node.js…",
    openToLabel: "Open to work",
    openToSub: "Show badge on your card",
    placeholderTitle: "Full-Stack Engineer",
    placeholderBio: "I build web apps and love open source. TypeScript + Next.js.",
  },
  {
    id: "creative",
    label: "Creative",
    description: "Designers, artists & creators",
    color: "#8b5cf6",
    titleLabel: "Specialty",
    tagLabel: "Tools & Mediums",
    tagPlaceholder: "Figma, Illustrator, Blender…",
    placeholderTitle: "UI/UX Designer & Visual Artist",
    placeholderBio: "Crafting beautiful experiences. I turn ideas into visuals.",
  },
  {
    id: "student",
    label: "Student",
    description: "Students, researchers & academics",
    color: "#f59e0b",
    titleLabel: "Field of Study",
    tagLabel: "Skills & Interests",
    tagPlaceholder: "Machine Learning, Python, Research…",
    institutionLabel: "Institution / University",
    institutionPlaceholder: "MIT, Stanford, IIT Bombay…",
    openToLabel: "Open to internships",
    openToSub: "Show badge on your card",
    placeholderTitle: "Computer Science",
    placeholderBio: "Passionate about AI and distributed systems. Seeking internships.",
  },
  {
    id: "business",
    label: "Business",
    description: "Founders, freelancers & businesses",
    color: "#06b6d4",
    titleLabel: "Position",
    institutionLabel: "Company / Organization",
    institutionPlaceholder: "Acme Corp, Self-employed…",
    placeholderTitle: "Founder & CEO",
    placeholderBio: "Building the future. Let's connect and create something great.",
  },
];

export function getCardType(id) {
  return CARD_TYPES.find((t) => t.id === id) || CARD_TYPES[0];
}
